#!/bin/bash

version=`git describe --tags | grep -Eo "^([^-]*)*"`
name="radix-map-editor"
dir="addon"

cp LICENCE.md $dir/LICENCE.md

zip -R $name-$version.zip *.py *.xsd $dir/*/*.md $dir/*.md

rm $dir/LICENCE.md

exit 0
